config/routes.rb
Sample::Application.routes.draw do
  resources :categories

  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

 resources :reviews
devise_for :users, :controllers => { :omniauth_callbacks =>"users/omniauth_callbacks" }

 devise_for :users, :controllers => { omniauth_callbacks: 'omniauth_callbacks', registrations: 'registrations'}
match '/users/:id/finish_signup' => 'users#finish_signup', via: [:get, :patch], :as => :finish_signup
  resources :articles

  resources :products do 

  resources :reviews
end

   root :to => 'products#index'
get '/pro', to: 'categories#pro'
  post '/pro', to: 'categories#pro'
  get '/click', to: 'categories#click'
  post '/click', to: 'categories#click'

end

app/models/product.rb
class Product < ActiveRecord::Base
	has_many :reviews
	belongs_to :category
	 validates :image,:name,:description,:category_id, presence: true
  attr_accessible :description, :name,:category_id
   attr_accessible :image
  has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/

 



end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  # GET /products
  # GET /products.json
    load_and_authorize_resource
  def index
    @products = Product.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @products }
    end
  end

  # GET /products/1
  # GET /products/1.json
  def show
    @product = Product.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @product }
    end
  end

  # GET /products/new
  # GET /products/new.json
  def new
    @product = Product.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @product }
    end
  end

  # GET /products/1/edit
  def edit
    @product = Product.find(params[:id])
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(params[:product])

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render json: @product, status: :created, location: @product }
      else
        format.html { render action: "new" }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /products/1
  # PUT /products/1.json
  def update
    @product = Product.find(params[:id])

    respond_to do |format|
      if @product.update_attributes(params[:product])
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product = Product.find(params[:id])
    @product.destroy

    respond_to do |format|
      format.html { redirect_to products_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<%= form_for(@product,:html => { :multipart => true }) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
 <div class="field">
     <div class="col-xs-6 col-md-8"> <%= f.label :category_name  %><br></div>
     <div class="col-xs-6 col-md-8"> <%= collection_select(:product ,:category_id,  Category.all,  :id, :name,prompt: "Select Category") %> </div>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  
  <div class="field">
    <%= f.label :image %><br />
    <%= f.file_field :image  %>
  </div>
 

  <div class="actions">
    <%= f.submit %>
  </div>
  <div ></div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing product</h1>

<%= render 'form' %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<h1>Listing products</h1>

<table class="table">
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th>Category</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @products.each do |product| %>
  <tr>
    <td><%= product.name %></td>

    <td><%= product.description %></td>

     <% @cat=Category.where(:id=>product.category_id).first %>

    <td><%=@cat.name %></td>
     
    <td><%= link_to 'Show', product %></td>
    <td><%= link_to 'Edit', edit_product_path(product) %></td>
    <%if current_user.role !="admin" %>
    <td><%= link_to 'Review the Product', new_product_review_path(product) %></td>
    <%end%>
    <%if current_user.role == 'admin' %>
    <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    <%end%>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Product', new_product_path %>

app/views/products/new.html.erb
<h1>New product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @product.name %>
</p>

<p>
  <b>Description:</b>
  <%= @product.description %>
</p>
<p>

<%= image_tag @product.image.url(:thumb) %>
</p>
<%if current_user.role =="admin"%>
<%= link_to 'Edit', edit_product_path(@product) %> |<%= link_to 'Back', products_path %>
<%end %>
<%if @product.reviews.any? %>
 <% @product_reviews=@product.reviews %>


<br>
<b>Product reviews</b>
<% @product_reviews.each do |product_review|%>
 <br><b>review:</b><%=product_review.description %>
<br><b>rating:</b><%=product_review.rating %>
<%end%>
<%else%>
<p>No Reviews available</p>
<%end%>
<br>