config/routes.rb
Sample::Application.routes.draw do
  resources :categories

  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

 resources :reviews
devise_for :users, :controllers => { :omniauth_callbacks =>"users/omniauth_callbacks" }

 devise_for :users, :controllers => { omniauth_callbacks: 'omniauth_callbacks', registrations: 'registrations'}
match '/users/:id/finish_signup' => 'users#finish_signup', via: [:get, :patch], :as => :finish_signup
  resources :articles

  resources :products do 

  resources :reviews
end

   root :to => 'products#index'
get '/pro', to: 'categories#pro'
  post '/pro', to: 'categories#pro'
  get '/click', to: 'categories#click'
  post '/click', to: 'categories#click'

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  load_and_authorize_resource
 
  before_filter :set_review, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    if current_user.role  != ""
      @reviews = Review.all
     else
      @reviews=Review.where(:user_id=>current_user.id)
     end
   
    respond_with(@reviews)
  end

  def show
    respond_with(@review)
     
  end

  def new
    @review = Review.new
    respond_with(@review)
  end

  def edit
  end

  def create
     if params[:product_id]
            @review.product_id=params[:product_id]
          end
    @review = Review.new(params[:review])
          if params[:product_id]
            @review.product_id=params[:product_id]
          end
    @review.save

    respond_with(@review)
  end

  def update
    @review.update_attributes(params[:review])
    respond_with(@review)
  end

  def destroy
    @review.destroy
    respond_with(@review)
  end

  private
    def set_review
      @review = Review.find(params[:id])
    end
end

app/views/reviews/_form.html.erb
<%= form_for(@review) do |f| %>
  <% if @review.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@review.errors.count, "error") %> prohibited this review from being saved:</h2>

      <ul>
      <% @review.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :rating %><br />
    <%= f.number_field :rating %>
  </div>
<%if params[:product_id]%>
<%= f.hidden_field :product_id ,:value=>params[:product_id]%>
<%= f.hidden_field :user_id ,:value=>current_user.id%>
<%end%>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/reviews/edit.html.erb
<h1>Editing review</h1>

<%= render 'form' %>

<%= link_to 'Show', @review %> |
<%= link_to 'Back', reviews_path %>

app/views/reviews/index.html.erb
<%if @reviews.blank? %>
You Are not given Reviews
<%else%>

<h1>Listing reviews</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Description</th>
    <th>Rating</th>
    <th>Product</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @reviews.each do |review| %>
  <tr>
    <td><%= review.title %></td>
    <td><%= review.description %></td>
    <td><%= review.rating %></td>
     <% @p= Product.where(:id=>review.product_id).first %>
       
    <td><%= @p.name %></td>

    <td><%= link_to 'Show', review %></td>
    <%if review.user_id == current_user.id  %>
    <td><%= link_to 'Edit', edit_review_path(review) %></td>
    <td><%= link_to 'Destroy', review, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    <%end%>
    
  </tr>
<% end %>
</table>

<br />
<%end%>
<%#= link_to 'New Review', new_review_path %>

app/views/reviews/new.html.erb
<h1>New review</h1>

<%= render 'form' %>

<%= link_to 'Back', reviews_path %>

app/views/reviews/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @review.title %>
</p>

<p>
  <b>Description:</b>
  <%= @review.description %>
</p>

<p>
  <b>Rating:</b>
  <%= @review.rating %>
</p>


<%= link_to 'Back', reviews_path %>